---
anchor-sections: false
format:
  html:
    theme: lux
    css: styles.css
    toc: false
    page-layout: full
---

<!-- ---TOP ROW ---------------------------------------------------------------------------------------------------------------------------------- -->
::: {style="display: grid; grid-template-columns: 1.5fr 1fr; gap: 2rem; margin-top: 2rem;"}

<!-- Left Card with Dimmed Image and Text Overlay -->
::: {.image-card}
<div class="overlay-card">
  <h2>Providing satellite data for the coastal ocean</h2>
  <p>View and download over 800 regional and global datasets, including satellite data, model output, and in-situ measurements.</p>
  <a href="data_catalog.qmd" class="btn-primary">View Data Catalog</a>
  <a href="#" class="btn-secondary">Coastal Conditions</a>
</div>
:::

<!-- Right News Card -->
::: {.news-card}
<div style="margin-bottom: 1rem"; class="news-header">
  <h3 style="margin 0;">News & Events</h3>
  <a href="#">View Archive</a>
</div>

<div class="news-item">
  <p class="news-title">New Publication on Alexandrium catenella Blooms</p>
  <p>Check out the <a href="https://www.sciencedirect.com/science/article/pii/S0301479725010187?via%3Dihub">new paper</a> with CoastWatch West Coast co-authors: Application of dinoflagellate-specific satellite models to aid bloom monitoring in the Bering and Chukchi seas.</p>
  <p class="news-date">March 24, 2025</p>
</div>

<div class="news-item">
  <p class="news-title">Spray Glider Dataset Available</p>
  <p>The <a href="https://coastwatch.pfeg.noaa.gov/wcn/erddap/tabledap/scrippsGlidersSQ.graph">Spray Glider dataset</a> from Scripps Institution of Oceanography is available for download on ERDDAP.</p>
  <p class="news-date">March 14, 2025</p>
</div>

<div class="news-item">
  <p class="news-title">WCN Project Dashboard Live</p>
  <p>Visit the CoastWatch West Coast Node (WCN) <a href="#">projects dashboard</a> for descriptions of and links to current projects.</p>
  <p class="news-date">February 21, 2025</p>
</div>
:::


:::


<!-- ---BOTTOM ROW ---------------------------------------------------------------------------------------------------------------------------------- -->
::: {style="display: grid; grid-template-columns: 1fr 1fr; gap: 2rem; margin-top: 2rem;"}
  
::: {.card}
<h3>ERDDAP Data Server</h3>
<p>The ERDDAP data server provides a simple, consistent way to subset and download environmental datasets in common file formats with options to make graphs and maps.</p>
<a href="https://coastwatch.pfeg.noaa.gov/erddap/index.html" class="btn-primary">ERDDAP Server</a>
<a href="data_server.qmd" class="btn-secondary">Learn More</a>
:::

::: {.card}
<h3>Software</h3>
<p>The Environmental Data Connector (EDC) and Xtractomatic data extraction scripts make it easy to discover and extract data from online servers and download them directly into ArcGIS, R, MatLab, and Excel.</p>
<a href="#" class="btn-primary">EDC</a>
<a href="#" class="btn-secondary">Xtractomatic</a>
:::
:::